### PR TITLE
Feature/receive pi transactions

### PR DESCRIPTION
**Pull request by DarinHajou**

### CODE REVIEW

**Review by swoocn — COMMENTED** [review]
Thank you @DarinHajou!
I appreciate your code contribution.  I will work on adapting it to fit within our Angular framework.  Just a gentle reminder, the frontend-orig folder contains the initial demo code.  Going forward, all frontend development should be implemented in the folder labeled 'frontend'.  Thanks again!

**Comment by swoocn** [comment]
Think I need some assistance here @zolcsi .  While I've successfully converted the Vanilla JS to the Angular Framework, I've noticed that not all styles are being applied as expected.  Perhaps you see something that I don't..?
Screenshot of the Transactions feature below ->

image

**Comment by swoocn** [comment]
Perhaps also worth mentioning that the build failed due to 
_Application bundle generation failed. [10.371 seconds]
Error: R] css-inline-fonts:https://fonts.googleapis.com/css2?family=Lato&display=swap exceeded maximum budget. Budget 4.00 kB was not met by 989 bytes with a total of 4.97 kB._

Do we need to increase the threshold again @zolcsi ..?

**Comment by DarinHajou** [comment]
> Thank you @DarinHajou! I appreciate your code contribution. I will work on adapting it to fit within our Angular framework. Just a gentle reminder, the frontend-orig folder contains the initial demo code. Going forward, all frontend development should be implemented in the folder labeled 'frontend'. Thanks again!



> Thank you @DarinHajou! I appreciate your code contribution. I will work on adapting it to fit within our Angular framework. Just a gentle reminder, the frontend-orig folder contains the initial demo code. Going forward, all frontend development should be implemented in the folder labeled 'frontend'. Thanks again!


Thanks for the feedback Danny. I'll make sure to work on the Frontend folder going forward! 🖥️ 🤗

**Comment by zolcsi** [comment]
> Think I need some assistance here @zolcsi . While I've successfully converted the Vanilla JS to the Angular Framework, I've noticed that not all styles are being applied as expected. Perhaps you see something that I don't..? Screenshot of the Transactions feature below ->
> 
> image

Thank you guys, I take a look and see what problems it has, but seemingly minor

**Comment by zolcsi** [comment]
> Perhaps also worth mentioning that the build failed due to _Application bundle generation failed. [10.371 seconds] Error: R] css-inline-fonts:https://fonts.googleapis.com/css2?family=Lato&display=swap exceeded maximum budget. Budget 4.00 kB was not met by 989 bytes with a total of 4.97 kB._
> 
> Do we need to increase the threshold again @zolcsi ..?

Yes, it was increased in the other PR, I merged it in for convenience, feel free to commit it regardless

**Review by zolcsi — APPROVED** [review]
Does it work as intended? If so, from my side it's ok :)

**Comment by swoocn** [comment]
> Does it work as intended? If so, from my side it's ok :)

Thx @zolcsi!
I managed to fix the test to stabilize the CI/CD pipeline, however, it appears that the issue with the transactions feature I mentioned earlier has not been resolved.  Despite having all the .scss files in place, the formatting styles such as button display and alignment are not being applied.  I will try to take a look at this some more later today.  Thx!

**Comment by swoocn** [comment]
It appears the formatting matter is resolved after removing the nested styling in SCSS.  Could be due to how SCSS compiles nested selectors into CSS..?  @DarinHajou - can you confirm that this display is what you expect?

image

**Comment by swoocn** [comment]
Handled in **feature/move-pi-transactions-to-correct-folder** branch.

**Pull request closed without merging**
